version: '3'
services:

  flask:
    build:
      context: flask-api
      dockerfile: Dockerfile-backend
    container_name: flask
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "False"
      APP_PORT: 5000
      MONGODB_DATABASE: flaskdb
      MONGODB_USERNAME: flaskuser
      MONGODB_PASSWORD: my_mongo_password_524
      MONGODB_HOSTNAME: mongodb
    volumes:
     # - flask-api:/var/www/app/app
     - /home/ec2-user/AttEx/flask-api:/var/www/app/app
    depends_on:
      - mongodb
    networks:
      - frontend
      - backend

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodbuser
      MONGO_INITDB_ROOT_PASSWORD: my_mongo_password_524
      MONGO_INITDB_DATABASE: flaskdb
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    ports:
      - "27017:27017"
      volumes:
      - ./mongodb:/data/db
    networks:
      - backend

  webserver:
    build:
      context: react-app
      dockerfile: Dockerfile
    container_name: webserver
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      APP_NAME: "webserver"
      APP_DEBUG: "true"
      SERVICE_NAME: "webserver"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./react-app/production.conf:/etc/nginx/conf.d/default.conf
      - ./react-app/dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/www.expert-annotation.com/fullchain.pem:/etc/letsencrypt/live/www.expert-annotation.com/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/www.expert-annotation.com/privkey.pem:/etc/letsencrypt/live/www.expert-annotation.com/privkey.pem
    depends_on:
      - flask
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge